### ISSUE TITLE
Incompatibility with networkx 2.x

### ISSUE THREAD

**Issue by kingjin94** [slivingston/gr1py#4]
Hi there,

I stumbled upon an issue with the optional dependency networkx in version 2.x, which is for example installed with scikit-image, and then kills gr1py. As a workaround I removed the import of the optional networkx in tstruct.py & solve.py and defaulted to .minnx for the DiGraph import.

Better solution would prbably require following this guide: https://networkx.github.io/documentation/latest/release/migration_guide_from_1.x_to_2.0.html

**Comment by slivingston** [comment]
Thanks for reporting this. Can you confirm which version of gr1py that you have? The recent release at <https://pypi.org/project/gr1py/0.3.0/> should have addressed compatibility with NetworkX 2.

If the error remains, can you give me some example code that demonstrates it?

**Comment by kingjin94** [comment]
This seems to be the issue; have installed it a few weeks ago when 0.2.0 was still the one in pip.
